// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONERI.Data;

#nullable disable

namespace ONERI.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    [Migration("20260122110027_Bolum_Alanlari_Eklendi")]
    partial class Bolum_Alanlari_Eklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ONERI.Models.BolumYonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoneticiAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoneticiEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BolumYoneticileri");
                });

            modelBuilder.Entity("ONERI.Models.Degerlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtkiPuani")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GayretPuani")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KurulYorumu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OneriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrijinallikPuani")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToplamPuan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UygulanabilirlikPuani")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OneriId");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("ONERI.Models.Oneri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltBolum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalistigiBolum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnerenKisi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oneriler");
                });

            modelBuilder.Entity("ONERI.Models.Degerlendirme", b =>
                {
                    b.HasOne("ONERI.Models.Oneri", "Oneri")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("OneriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oneri");
                });

            modelBuilder.Entity("ONERI.Models.Oneri", b =>
                {
                    b.Navigation("Degerlendirmeler");
                });
#pragma warning restore 612, 618
        }
    }
}
